---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'COPYING'
      - 'LICENSES/**'
      - 'NEWS'
      - 'README.md'
      - 'build/**'
      - 'doc/**'
      - 'subprojects/**'
      - 'systemd/**'
      - 'win32/**'
    branches:
      - master
      - v0.24.x
  pull_request:
    paths-ignore:
      - 'AUTHORS'
      - 'COPYING'
      - 'LICENSES/**'
      - 'NEWS'
      - 'README.md'
      - 'build/**'
      - 'doc/**'
      - 'subprojects/**'
      - 'systemd/**'
      - 'win32/**'
    branches:
      - master
      - v0.24.x

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build-android:
    strategy:
      matrix:
        abi: [arm64-v8a, x86_64]

    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@v7

      - name: "Cache third-party library tarballs"
        uses: actions/cache@v6
        with:
          key: lib-tarballs-android-${{hashFiles('android/build.py', 'python/**')}}
          path: |
            ${{github.workspace}}/output/lib/download

      - name: "Cache third-party libraries"
        uses: actions/cache@v6
        with:
          key: libs-android-${{matrix.abi}}-${{hashFiles('android/build.py', 'python/**')}}
          path: |
            ${{github.workspace}}/output/lib/*/root

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache \
            nasm \
            quilt 

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: android

      - name: Build
        run: |
          mkdir -p output
          cd ./output
          ../android/build.py $ANDROID_SDK_ROOT $ANDROID_NDK_HOME ${{matrix.abi}} \
            --buildtype=debugoptimized -Db_ndebug=true \
            -Dwrap_mode=forcefallback 

      - name: Build Java
        run: |
          cd ./android
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./gradlew assembleDebug

